const fs = require('fs-extra');
fs.mkdirSync('Folder_1'); 
    console.log('Folder_1 created successfully!');
fs.writeFileSync('Folder_1/file1.txt', "Hello IT-Academy!"); 
    console.log('.txt file in Folder_1 created successfully!');
fs.mkdirSync('Folder_2'); 
    console.log('Folder_2 created successfully!');
fs.moveSync('Folder_1/file1.txt', 'Folder_2/file1.txt'); 
    console.log('File.txt successfully removed from Folfer_1 to Folder_2 !');
fs.mkdirSync('Folder_3'); 
    console.log('Folder_3 created successfully!');
fs.copySync('Folder_2/file1.txt', 'Folder_3/file2.txt'); 
    console.log ('file copyed');
fs.rmSync('./Folder_2/file1.txt'); 
    console.log('file1 was deleted successfully!');
fs.rmSync('./Folder_3/file2.txt'); 
    console.log('file1 was deleted successfully!');
fs.rmdirSync('Folder_1');
    console.log('Folder_1 was deleted successfully!');
fs.rmdirSync('Folder_2');
    console.log('Folder_2 was deleted successfully!');
fs.rmdirSync('Folder_3');
    console.log('Folder_3 was deleted successfully!');